name: Java CI without Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Compile Java code
      run: javac SistemaHospital.java

    - name: Run unit tests
      run: java SistemaHospitalTest # Asegúrate de tener un archivo de pruebas para tu clase




